//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5_Proje1.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MV5_Proje1Entities : DbContext
    {
        public MV5_Proje1Entities()
            : base("name=MV5_Proje1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_Cezalar> TBL_Cezalar { get; set; }
        public virtual DbSet<TBL_Kasa> TBL_Kasa { get; set; }
        public virtual DbSet<TBL_Kategori> TBL_Kategori { get; set; }
        public virtual DbSet<TBL_Kitap> TBL_Kitap { get; set; }
        public virtual DbSet<TBL_Uye> TBL_Uye { get; set; }
        public virtual DbSet<TBL_Yazar> TBL_Yazar { get; set; }
        public virtual DbSet<TBL_Hareket> TBL_Hareket { get; set; }
        public virtual DbSet<TBL_Personel> TBL_Personel { get; set; }
        public virtual DbSet<TBL_Hakkımızda> TBL_Hakkımızda { get; set; }
        public virtual DbSet<TBL_ILETISIM> TBL_ILETISIM { get; set; }
        public virtual DbSet<TBL_Mesajlar> TBL_Mesajlar { get; set; }
        public virtual DbSet<TBL_DUYURULAR> TBL_DUYURULAR { get; set; }
        public virtual DbSet<TBL_Admin> TBL_Admin { get; set; }
    
        public virtual ObjectResult<string> EnFazlaKitapYazar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("EnFazlaKitapYazar");
        }
    }
}
