//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5_Proje1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Personel()
        {
            this.TBL_Hareket = new HashSet<TBL_Hareket>();
        }
    
        public byte Personelid { get; set; }
        public string PersonelAdSoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Hareket> TBL_Hareket { get; set; }
    }
}
