//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5_Proje1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Hareket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Hareket()
        {
            this.TBL_Cezalar = new HashSet<TBL_Cezalar>();
        }
    
        public int Hareketid { get; set; }
        public Nullable<int> Alınankitap { get; set; }
        public Nullable<int> Alanuye { get; set; }
        public Nullable<byte> Personel { get; set; }
        public Nullable<System.DateTime> AlısTarihi { get; set; }
        public Nullable<System.DateTime> iadetarihi { get; set; }
        public Nullable<bool> islemdurum { get; set; }
        public Nullable<System.DateTime> uyegetirtarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Cezalar> TBL_Cezalar { get; set; }
        public virtual TBL_Kitap TBL_Kitap { get; set; }
        public virtual TBL_Personel TBL_Personel { get; set; }
        public virtual TBL_Uye TBL_Uye { get; set; }
    }
}
