//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5_Proje1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Hakkımızda
    {
        public byte id { get; set; }
        public string aciklama { get; set; }
    }
}
