//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5_Proje1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Kitap()
        {
            this.TBL_Hareket = new HashSet<TBL_Hareket>();
        }
    
        public int Kitapid { get; set; }
        public string Kitapad { get; set; }
        public Nullable<int> Kitapkategori { get; set; }
        public Nullable<int> Kitapyazar { get; set; }
        public string Basımyıl { get; set; }
        public string Yayınevi { get; set; }
        public string Kitapsayfa { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string Kitapresim { get; set; }
    
        public virtual TBL_Kategori TBL_Kategori { get; set; }
        public virtual TBL_Yazar TBL_Yazar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Hareket> TBL_Hareket { get; set; }
    }
}
