//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5_Proje1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Uye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Uye()
        {
            this.TBL_Cezalar = new HashSet<TBL_Cezalar>();
            this.TBL_Hareket = new HashSet<TBL_Hareket>();
        }
    
        public int Uyeid { get; set; }
        public string Uyead { get; set; }
        public string Uyesoyad { get; set; }
        public string Uyemail { get; set; }
        public string Uyekullanıcıadı { get; set; }
        public string Uyekullanıcısifre { get; set; }
        public string UyeFotograf { get; set; }
        public string Uyetelefon { get; set; }
        public string UyeOkul { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Cezalar> TBL_Cezalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Hareket> TBL_Hareket { get; set; }
    }
}
